version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-bob-whisky-expert-secret}
    volumes:
      - ./bob_cache.db:/app/bob_cache.db